# Trained with Tesla V100 (32GB) x 4 GPUs. It takes about 3.5 days.
encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.2
    positional_dropout_rate: 0.2
    attention_dropout_rate: 0.2
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.2
    positional_dropout_rate: 0.2
    self_attention_dropout_rate: 0.2
    src_attention_dropout_rate: 0.2

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    hop_length: 160

use_amp: true
num_workers: 4
batch_type: numel
batch_bins: 30000000    #35,00 0,000(초기설정)50000000(finetune)
accum_grad: 4
max_epoch: 130 #50 원래 50 
patience: 50
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.003  #0.0005
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 75000 #75000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30 #30
    num_freq_mask: 6
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40 #40
    num_time_mask: 2 #2 
